# -*- coding: utf-8 -*-
"""rainfall_dasboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RexXpaBF2vdlXKBGVUTuqcg2BNBFoOzc

TASK 1: Data Cleaning & Preprocessing for the Rainfall dataset.
"""

import pandas as pd
import numpy as np

# Load data
df = pd.read_csv("/content/rainfall in india 1901-2015 (1).csv")

print("📂 First 5 rows:")
display(df.head())

print("\n📏 Dataset Shape:", df.shape)

print("\n🔍 Column Info:")
df.info()

# Check missing values
print("\n❓ Missing Values:")
print(df.isnull().sum())

# Option 1: Drop rows with null values
df = df.dropna()

# Option 2 (Alternative): Fill missing using mean
# df = df.fillna(df.mean())

print("\n🧹 Duplicates removed:", df.duplicated().sum())
df = df.drop_duplicates()

df['YEAR'] = df['YEAR'].astype(int)   # Year should be integer
df = df.apply(pd.to_numeric, errors='ignore')  # Convert numeric columns properly

df.columns = df.columns.str.replace(' ', '_').str.upper()

print("\n✅ Cleaned Dataset Info:")
df.info()

print("\n📂 Preview Cleaned Data:")
display(df.head())

"""First, we loaded the dataset and inspected its structure.

We checked and handled missing values, removed duplicates, and corrected datatypes.

Then we standardized column names for easier processing.

This ensures clean and reliable data for further EDA and machine-learning tasks.

TASK 2:Exploratory Data Analysis (EDA) for the Rainfall dataset.

Summary statistics

Rainfall distribution plot

Seasonal rainfall comparison

Annual rainfall trend quick view
"""

# Summary of dataset
print("📈 Summary Statistics")
display(df.describe())

# Unique subdivisions count
print("\n🌍 Number of Indian Regions/Subdivisions:", df['SUBDIVISION'].nunique())

# Dataset period
print(f"\n📅 Data Range: {df['YEAR'].min()} - {df['YEAR'].max()}")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df["ANNUAL"], bins=20, alpha=0.7)
plt.title("Distribution of Annual Rainfall in India (1901–2015)")
plt.xlabel("Annual Rainfall (mm)")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

import seaborn as sns

season_cols = ['JAN-FEB','MAR-MAY','JUN-SEP','OCT-DEC','ANNUAL']

plt.figure(figsize=(8,5))
sns.barplot(x=season_cols, y=df[season_cols].mean())
plt.title("Average Seasonal Rainfall in India (1901–2015)")
plt.ylabel("Average Rainfall (mm)")
plt.xlabel("Season")
plt.grid(True)
plt.show()

df_sorted = df.sort_values("YEAR")

plt.figure(figsize=(10,5))
plt.plot(df_sorted["YEAR"], df_sorted["ANNUAL"], color="purple", alpha=0.7)
plt.title("Annual Rainfall Trend (1901–2015)")
plt.xlabel("Year")
plt.ylabel("Annual Rainfall (mm)")
plt.grid(True)
plt.show()

top_regions = df.groupby("SUBDIVISION")["ANNUAL"].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,6))
sns.barplot(y=top_regions.index, x=top_regions.values)
plt.title("Top 10 Rainiest Regions in India (Avg Annual Rainfall)")
plt.xlabel("Average Annual Rainfall (mm)")
plt.ylabel("Subdivision")
plt.show()

"""During EDA, we examined rainfall distribution, seasonal averages, and long-term rainfall trends.

We visualized annual rainfall from 1901–2015 and compared seasonal contributions.

This helps understand monsoon dependency, drought years, and climate fluctuations in India.

TASK 3: Correlation Heatmap for your Rainfall in India (1901–2015) dataset.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Select only numerical seasonal & annual columns
season_cols = ['JAN-FEB','MAR-MAY','JUN-SEP','OCT-DEC','ANNUAL']
corr = df[season_cols].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", linewidths=.5)
plt.title("Correlation Heatmap — Seasonal vs Annual Rainfall")
plt.show()

"""We plotted a correlation heatmap for seasonal rainfall values.

It shows the strength of relationship between seasonal rainfall and annual rainfall.

The monsoon period (June-September) shows the highest correlation with annual rainfall, indicating India’s rainfall pattern is primarily monsoon-driven.

TASK 4: Time-Series Trend (Smoothed)

We will visualize long-term rainfall trend using moving average smoothing to understand climate pattern change over time.
"""

import matplotlib.pyplot as plt

# Sort by year to maintain time order
df = df.sort_values("YEAR")

# Create Moving Average Columns (5-year & 10-year)
df["MA_5"] = df["ANNUAL"].rolling(window=5).mean()
df["MA_10"] = df["ANNUAL"].rolling(window=10).mean()

# Plot
plt.figure(figsize=(10,5))
plt.plot(df["YEAR"], df["ANNUAL"], color="gray", alpha=0.4, label="Actual Annual Rainfall")
plt.plot(df["YEAR"], df["MA_5"], color="red", linewidth=2, label="5-Year Moving Average")
plt.plot(df["YEAR"], df["MA_10"], color="blue", linewidth=2, label="10-Year Moving Average")

plt.title("Smoothed Annual Rainfall Trend in India (1901–2015)")
plt.xlabel("Year")
plt.ylabel("Rainfall (mm)")
plt.grid(True)
plt.legend()
plt.show()

"""What this plot shows

Grey = actual rainfall (year-to-year fluctuation)

Red = 5-year trend (short-term climate trend)

Blue = 10-year trend (long-term climate trend)

📉 If the line slopes downward → long-term decrease in rainfall

📈 If rising → long-term increase

↕️ If flat → stable pattern

We smoothed annual rainfall series using 5-year and 10-year moving averages.
This removes short-term noise and highlights long-term climate trends.
The trend helps observe drought cycles, monsoon variation, and climate change signals.

TASK 5: Seasonal vs Annual Rainfall Comparison

This task helps show how each season contributes to the annual rainfall.
We will create:

Scatter plots with trendline (Season vs Annual)

Multi-line graph for seasonal rainfall across years
"""

import seaborn as sns
import matplotlib.pyplot as plt

season_cols = ['JAN-FEB','MAR-MAY','JUN-SEP','OCT-DEC']

for season in season_cols:
    plt.figure(figsize=(7,5))
    sns.regplot(x=df[season], y=df["ANNUAL"], scatter_kws={"alpha":0.5}, line_kws={'color':'red'})
    plt.title(f"{season} vs Annual Rainfall")
    plt.xlabel(f"{season} Rainfall (mm)")
    plt.ylabel("Annual Rainfall (mm)")
    plt.grid(True)
    plt.show()

"""Insight you will see

Jun-Sep (Monsoon) ≈ strongest effect on annual rainfall (steep trend line)

Winter (Jan-Feb) lowest impact
"""

df_sorted = df.sort_values("YEAR")

plt.figure(figsize=(12,6))

plt.plot(df_sorted["YEAR"], df_sorted["ANNUAL"], label="Annual", linewidth=2, color="black")

for season in season_cols:
    plt.plot(df_sorted["YEAR"], df_sorted[season], linewidth=1.6, alpha=0.8, label=season)

plt.title("Seasonal vs Annual Rainfall Trend (1901–2015)")
plt.xlabel("Year")
plt.ylabel("Rainfall (mm)")
plt.grid(True)
plt.legend()
plt.show()

"""We compared seasonal rainfall with annual rainfall using scatter plots and trendlines.
The monsoon season (June-September) shows a strong positive relationship with annual rainfall, confirming that India's rainfall is monsoon-driven.
A seasonal multi-line plot also shows long-term seasonal variation across decades.

TASK 6: Linear Regression to Predict Annual Rainfall
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import matplotlib.pyplot as plt

# Features (seasonal rainfall)
X = df[['JAN-FEB', 'MAR-MAY', 'JUN-SEP', 'OCT-DEC']]

# Target (annual rainfall)
y = df['ANNUAL']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation Metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("📊 Linear Regression Model Evaluation")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.4f}")

plt.figure(figsize=(7,5))
plt.scatter(y_test, y_pred, color="blue", alpha=0.6)
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--') # reference line
plt.title("Actual vs Predicted Annual Rainfall")
plt.xlabel("Actual Annual Rainfall")
plt.ylabel("Predicted Annual Rainfall")
plt.grid(True)
plt.show()

coeff = pd.DataFrame({"Season": X.columns, "Coefficient": model.coef_})
print("\nSeason Importance in Prediction:")
display(coeff)

"""We used Linear Regression to predict annual rainfall using seasonal rainfall values.
The model was trained on 80% of data and tested on 20%.
We evaluated the model using MAE, RMSE, and R² score.
The monsoon (Jun–Sep) contributed the most to annual rainfall prediction, proving India's dependence on monsoon systems

TASK 7: ARIMA Time-Series Forecasting to predict future rainfall.
"""

import pandas as pd

# Sort by year
df = df.sort_values("YEAR")

# Set YEAR column as index (important for ARIMA)
ts = df.set_index("YEAR")["ANNUAL"]

# Display first values
ts.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(ts, label="Annual Rainfall")
plt.title("Annual Rainfall in India (1901–2015)")
plt.xlabel("Year")
plt.ylabel("Rainfall (mm)")
plt.grid(True)
plt.legend()
plt.show()

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(ts, order=(1,1,1))
model_fit = model.fit()
print(model_fit.summary())

# Forecast next 10 years
forecast = model_fit.forecast(steps=10)

print("\n📈 Rainfall Forecast for Next 10 Years:")
print(forecast)

plt.figure(figsize=(10,5))
plt.plot(ts, label="Actual Rainfall")
plt.plot(range(ts.index[-1]+1, ts.index[-1]+1+10), forecast, label="Forecast", color='red', marker='o')

plt.title("Rainfall Forecast (ARIMA Model)")
plt.xlabel("Year")
plt.ylabel("Rainfall (mm)")
plt.grid(True)
plt.legend()
plt.show()

"""We used ARIMA time-series model to forecast Indian rainfall.
We converted the annual rainfall column into a time-series indexed by year, trained an ARIMA(1,1,1) model, and predicted future values.
ARIMA captures trend and past patterns to produce forecast values, helping detect long-term rainfall shifts and climate change patterns.

TASK 8: K-Means Rainfall Pattern Clustering
"""

import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

# Use seasonal + annual columns for clustering
features = ['JAN-FEB','MAR-MAY','JUN-SEP','OCT-DEC','ANNUAL']

X = df[features]

# Determine optimal number of clusters using the elbow method
inertia = []
for n_clusters in range(1, 11):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(range(1, 11), inertia, marker='o')
plt.title('Elbow Method for Optimal Number of Clusters')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
df['Rainfall_Cluster'] = kmeans.fit_predict(X_scaled)
df['Rainfall_Cluster'].value_counts()

# Sort clusters by mean annual rainfall for meaningful label assignment
cluster_mean = df.groupby('Rainfall_Cluster')['ANNUAL'].mean().sort_values()

mapping = {cluster_mean.index[0]:"Low Rainfall",
           cluster_mean.index[1]:"Moderate Rainfall",
           cluster_mean.index[2]:"High Rainfall"}

df['Rainfall_Level'] = df['Rainfall_Cluster'].map(mapping)

df[['YEAR','ANNUAL','Rainfall_Level']].head()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
for level, color in zip(["Low Rainfall","Moderate Rainfall","High Rainfall"], ['red','orange','green']):
    subset = df[df['Rainfall_Level']==level]
    plt.scatter(subset['JUN-SEP'], subset['ANNUAL'], label=level, alpha=0.7)

plt.title("K-Means Rainfall Clusters (India)")
plt.xlabel("Monsoon Rainfall (Jun-Sep)")
plt.ylabel("Annual Rainfall")
plt.legend()
plt.grid(True)
plt.show()

"""We applied K-Means clustering on seasonal and annual rainfall data to group years into Low, Moderate, and High rainfall categories.
We first standardized the values, then clustered into 3 groups.
The scatter plot shows how monsoon rainfall strongly influences annual rainfall.
This helps detect drought years, normal years, and wet years.

TASK 9: Outlier / Drought / Flood Year Detection
"""

import numpy as np

# Select annual rainfall
annual = df["ANNUAL"]

# IQR
Q1 = annual.quantile(0.25)
Q3 = annual.quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Detect outliers
drought_years = df[df["ANNUAL"] < lower_limit][["YEAR","ANNUAL"]]
flood_years   = df[df["ANNUAL"] > upper_limit][["YEAR","ANNUAL"]]

print("🌵 Drought Years (Low Rainfall):")
print(drought_years)

print("\n🌊 Flood/Heavy Rainfall Years:")
print(flood_years)

from scipy import stats

df["Zscore"] = stats.zscore(df["ANNUAL"])

drought_z = df[df["Zscore"] < -2][["YEAR","ANNUAL"]]
flood_z   = df[df["Zscore"] > 2][["YEAR","ANNUAL"]]

print("\n🌵 Drought Years (Z-Score < -2):")
print(drought_z)

print("\n🌊 Flood Years (Z-Score > 2):")
print(flood_z)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))
plt.boxplot(df["ANNUAL"])
plt.title("Boxplot — Annual Rainfall in India")
plt.ylabel("Rainfall (mm)")
plt.grid(True)
plt.show()

plt.figure(figsize=(12,5))
plt.plot(df["YEAR"], df["ANNUAL"], label="Annual Rainfall", color='blue')

plt.scatter(drought_years["YEAR"], drought_years["ANNUAL"], color='red', s=80, label="Drought Years")
plt.scatter(flood_years["YEAR"], flood_years["ANNUAL"], color='green', s=80, label="Flood Years")

plt.title("Rainfall Trend Highlighting Drought & Flood Years")
plt.xlabel("Year")
plt.ylabel("Annual Rainfall (mm)")
plt.legend()
plt.grid(True)
plt.show()

"""We detected unusual rainfall years using IQR and Z-score methods.
Years falling below the lower bound are classified as drought years, while those above the upper bound are flood years.
We visualized these years on a boxplot and time-series graph to study climate anomalies.

TASK 10: Streamlit Dashboard for your Rainfall in India (1901-2015) dataset
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
@st.cache_data
def load_data():
    df = pd.read_csv("rainfall in india 1901-2015 (1).csv")
    df = df.sort_values("YEAR")
    return df

df = load_data()

st.title("🌧️ Rainfall in India Dashboard (1901–2015)")
st.write("Interactive visualization & analysis of rainfall trends in India.")

# Sidebar filters
st.sidebar.header("Filters")
year_range = st.sidebar.slider("Select Year Range", int(df.YEAR.min()), int(df.YEAR.max()),
                               (int(df.YEAR.min()), int(df.YEAR.max())))

filtered_df = df[(df["YEAR"] >= year_range[0]) & (df["YEAR"] <= year_range[1])]

# Dataset Preview
st.subheader("📂 Dataset Preview")
st.dataframe(filtered_df.head())

# Line Chart - Annual Rainfall Trend
st.subheader("📈 Annual Rainfall Trend")
fig, ax = plt.subplots(figsize=(10,4))
ax.plot(filtered_df["YEAR"], filtered_df["ANNUAL"], linewidth=2)
ax.set_xlabel("Year")
ax.set_ylabel("Rainfall (mm)")
ax.grid(True)
st.pyplot(fig)

# Seasonal Average Plot
st.subheader("🌦️ Seasonal Rainfall Comparison")
season_cols = ['Jan-Feb','Mar-May','Jun-Sep','Oct-Dec']
season_avg = filtered_df[season_cols].mean()

fig2, ax2 = plt.subplots(figsize=(6,4))
sns.barplot(x=season_avg.index, y=season_avg.values, ax=ax2)
ax2.set_ylabel("Average Rainfall (mm)")
ax2.set_title("Average Seasonal Rainfall")
st.pyplot(fig2)

# Boxplot for Annual Rainfall
st.subheader("📦 Distribution of Annual Rainfall")
fig3, ax3 = plt.subplots(figsize=(4,4))
sns.boxplot(y=filtered_df["ANNUAL"], ax=ax3)
ax3.set_ylabel("Rainfall (mm)")
st.pyplot(fig3)

# Download dataset
@st.cache_data
def convert_df(df):
    return df.to_csv(index=False).encode('utf-8')

csv = convert_df(filtered_df)
st.download_button("📥 Download Filtered Data", csv, "filtered_rainfall.csv", "text/csv")

# Forecast placeholder
st.subheader("🔮 Forecasting (Coming Soon)")
st.info("Future rainfall prediction will be added with ARIMA / ML model output.")

st.write("✅ Dashboard Complete — Use filters from left panel")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

"""I created an interactive rainfall dashboard using Streamlit. It allows users to filter years, view rainfall trends, analyze seasonal contributions, check data distribution, and download filtered results.
This helps understand climate patterns in India and supports rainfall analytics and prediction studies.
"""